### ISSUE TITLE
[Turk][Bug report] "left" gets converted to "leave" in postprocessed logical form

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#323] opened 2021-04-15 01:46 UTC
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

For command "move left", 
```
INFO:root:logical form post-coref "5c22a26c9acc7cdc0fc8a21e35cce95fff34d9b7cd339df2cb87f582c7276f6e:13cfd6b70502440987a0b4417fc89cea" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'MOVE', 'location': {'reference_object': {'special_reference': '-90'}, 'relative_direction': 'LEFT', 'text_span': 'leave'}}]}
2021-04-13 09:46:51,981 [nsp_dialogue_manager.py:172 - handle_logical_form() INFO]: logical form post-coref "5c22a26c9acc7cdc0fc8a21e35cce95fff34d9b7cd339df2cb87f582c7276f6e:13cfd6b70502440987a0b4417fc89cea" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'MOVE', 'location': {'reference_object': {'special_reference': '-90'}, 'relative_direction': 'LEFT', 'text_span': 'leave'}}]}
INFO:root:Sending chat: I think you are pointing at something but I don't know what it is
2021-04-13 09:46:51,982 [craftassist_agent.py:267 - send_chat() INFO]: Sending chat: I think you are pointing at something but I don't know what it is
```

**Comment by aszlam** [comment] 2021-04-19 11:41
I don't think this is a post-processing bug (this is expected behavior).  it does look like a ttad bug- what is 'reference_object': {'special_reference': '-90'} ?

**Comment by kavyasrinet** [comment] 2021-04-19 18:16
>  it does look like a ttad bug- what is 'reference_object': {'special_reference': '-90'} ?
To me this sounds like the mishap that happened with locobot.txt . @Rebecca-Qian  can you confirm ? Have we deployed the new locobot.txt ? We should check if this is happening again

**Comment by kavyasrinet** [comment] 2021-05-07 19:51
Closing this issue since this ins't a preprocessing bug.

**Closed by kavyasrinet** 2021-05-07 19:51 UTC
Labels: bug report
